export default {
    extends: ["@commitlint/config-conventional", "gitmoji"],
    rules: {
        //"signed-off-by": [2, "always", "Signed-off-by:"],
        "type-enum": [
            2,
            "always",
            ["build", "ci", "docs", "feat", "fix", "perf", "refactor", "revert", "style", "test", "wip", "merge", "chore"],
        ],
    },
    prompt: {
        alias: { fd: 'docs: fix typos' },
        messages: {
            type: '选择你要提交的类型:',
            scope: '选择一个提交范围 (可选):',
            customScope: '请输入自定义的提交范围:',
            subject: '填写简短精炼的变更描述:\n',
            body: '填写更加详细的变更描述 (可选)。使用 "|" 换行:\n',
            breaking: '列举非兼容性重大的变更 (可选)。使用 "|" 换行:\n',
            footer: '列举出所有变更的 ISSUES CLOSED (可选)。 例如: #31, #34:\n',
            confirmCommit: '确认提交?',
        },
        types: [
            { value: 'feat', name: 'feat:     ✨  新增功能', emoji: '✨' },
            { value: 'fix', name: 'fix:      🐛  修复缺陷', emoji: '🐛' },
            { value: 'docs', name: 'docs:     📝  文档变更', emoji: '📝' },
            { value: 'style', name: 'style:    🎨  代码格式', emoji: '🎨' },
            { value: 'refactor', name: 'refactor: ♻️   代码重构', emoji: '♻️' },
            { value: 'perf', name: 'perf:     ⚡️  性能优化', emoji: '⚡️' },
            { value: 'test', name: 'test:     ✅  添加疏漏测试或已有测试改动', emoji: '✅' },
            { value: 'build', name: 'build:    📦️  构建流程、外部依赖变更', emoji: '📦️' },
            { value: 'ci', name: 'ci:       🎡  修改 CI 配置、脚本', emoji: '🎡' },
            { value: 'chore', name: 'chore:    🔨  对构建过程或辅助工具和库的更改', emoji: '🔨' },
            { value: 'revert', name: 'revert:   ⏪️  回滚 commit', emoji: '⏪️' },
        ],
        useEmoji: true,
        emojiAlign: 'center',
        themeColorCode: '',
        scopes: ['root', 'core', 'mcp', 'llm', 'memory', 'config'],
        allowCustomScopes: true,
        allowEmptyScopes: true,
        customScopesAlign: 'bottom',
        customScopesAlias: 'custom',
        emptyScopesAlias: 'empty',
        upperCaseSubject: false,
        markBreakingChangeMode: false,
        allowBreakingChanges: ['feat', 'fix'],
        breaklineNumber: 100,
        breaklineChar: '|',
        skipQuestions: [],
        issuePrefixes: [{ value: 'closed', name: 'closed:   ISSUES has been processed' }],
        customIssuePrefixAlign: 'top',
        emptyIssuePrefixAlias: 'skip',
        customIssuePrefixAlias: 'custom',
        allowCustomIssuePrefix: true,
        allowEmptyIssuePrefix: true,
        confirmColorize: true,
        maxHeaderLength: Infinity,
        maxSubjectLength: Infinity,
        minSubjectLength: 0,
        scopeOverrides: undefined,
        defaultBody: '',
        defaultIssues: '',
        defaultScope: '',
        defaultSubject: '',
    },
};
