blank_issues_enabled: false
contact_links:
  - name: Github Discussion
    url: https://github.com/YesWeAreBot/YesImBot/discussions
    about: Asking for help here | 在讨论区寻求别人的帮助
  - name: Official Docs
    url: https://docs.yesimbot.chat/
    about: Asking for help here | 在官方文档寻找解决方案
  - name: More
    url: https://qm.qq.com/q/x4v3y2Gr8m
    about: More YesImBot communities | 加入官方 QQ 群
